events {}
http {
  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth:5001/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/alerts/ {
      proxy_pass http://alert:5002/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
    }
  }
}
